
#use the official Node.js 18 Alpine image as the base image

FROM node:18-alpine

WORKDIR /use/src/app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3003

CMD ["node","src/service.js"]